name: brainspire_mobile_app
description: A medical resource hub for MBBS students.

version: 1.0.0+1

environment:
  sdk: "^3.10.0"

dependencies:
  flutter:
    sdk: flutter

  supabase_flutter: ^2.5.0
  provider: ^6.1.2
  device_info_plus: ^10.1.0
  pdf: ^3.10.7
  printing: ^5.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
