// core/services/pdf_export_service.dart

import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';

class PDFExportService {
  Future<void> exportPYQs({
    required List<QuestionModel> questions,
    required PYQFilter filter,
  }) async {
    final doc = pw.Document();
    final font = await PdfGoogleFonts.notoSansRegular();
    final boldFont = await PdfGoogleFonts.notoSansBold();

    doc.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(36),
        header: (context) => _buildHeader(filter, boldFont),
        footer: (context) => _buildFooter(context, font),
        build: (context) => [
          pw.SizedBox(height: 16),
          ...questions.asMap().entries.map(
            (e) => _buildQuestionCard(e.key + 1, e.value, font, boldFont),
          ),
        ],
      ),
    );

    await Printing.layoutPdf(
      onLayout: (_) async => doc.save(),
      name: _buildFileName(filter),
    );
  }

  pw.Widget _buildHeader(PYQFilter filter, pw.Font boldFont) {
    final parts = <String>[];
    if (filter.subjectId != null) parts.add('Subject: ${filter.subjectId}');
    if (filter.year != null) parts.add('Year: ${filter.year}');
    if (filter.marks != null) parts.add('${filter.marks}m');

    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: [
        pw.Text(
          'Brainspire PYQ Export',
          style: pw.TextStyle(font: boldFont, fontSize: 18),
        ),
        pw.Text(
          parts.join(' · '),
          style: pw.TextStyle(fontSize: 11, color: PdfColors.grey600),
        ),
        pw.Divider(),
      ],
    );
  }

  pw.Widget _buildQuestionCard(
    int index,
    QuestionModel q,
    pw.Font font,
    pw.Font boldFont,
  ) {
    return pw.Container(
      margin: const pw.EdgeInsets.only(bottom: 16),
      padding: const pw.EdgeInsets.all(12),
      decoration: pw.BoxDecoration(
        border: pw.Border.all(color: PdfColors.grey300),
        borderRadius: const pw.BorderRadius.all(pw.Radius.circular(6)),
      ),
      child: pw.Column(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: [
          pw.Text(
            'Q$index. ${q.questionText}',
            style: pw.TextStyle(font: font, fontSize: 12),
          ),
          pw.SizedBox(height: 6),
          pw.Wrap(
            spacing: 6,
            children: [
              if (q.year != null) _tag('${q.year}', PdfColors.blue100),
              if (q.examType != null) _tag(q.examType!, PdfColors.green100),
              if (q.marks != null) _tag('${q.marks}m', PdfColors.orange100),
              if (q.topic != null) _tag(q.topic!, PdfColors.purple100),
            ],
          ),
          pw.SizedBox(height: 4),
          pw.Row(
            children: [
              pw.Text(
                '♥ ${q.likeCount}  🔖 ${q.bookmarkCount}',
                style: pw.TextStyle(
                  font: font,
                  fontSize: 9,
                  color: PdfColors.grey600,
                ),
              ),
            ],
          ),
        ],
      ),
    );
  }

  pw.Widget _tag(String label, PdfColor bg) => pw.Container(
    margin: const pw.EdgeInsets.only(right: 4, top: 4),
    padding: const pw.EdgeInsets.symmetric(horizontal: 6, vertical: 2),
    decoration: pw.BoxDecoration(
      color: bg,
      borderRadius: const pw.BorderRadius.all(pw.Radius.circular(4)),
    ),
    child: pw.Text(label, style: const pw.TextStyle(fontSize: 9)),
  );

  pw.Widget _buildFooter(pw.Context ctx, pw.Font font) => pw.Row(
    mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
    children: [
      pw.Text(
        'Generated by Brainspire',
        style: pw.TextStyle(font: font, fontSize: 9, color: PdfColors.grey),
      ),
      pw.Text(
        'Page ${ctx.pageNumber} of ${ctx.pagesCount}',
        style: pw.TextStyle(font: font, fontSize: 9, color: PdfColors.grey),
      ),
    ],
  );

  String _buildFileName(PYQFilter filter) {
    final parts = ['brainspire_pyq'];
    if (filter.year != null) parts.add('${filter.year}');
    if (filter.marks != null) parts.add('${filter.marks}m');
    return '${parts.join("_")}.pdf';
  }
}
